
# Sources
SRCS += color_palette.c


# Config
include $(ROOTDIR)/config.mk

# Includes
CFLAGS += -Iinc
#CFLAGS += -I../Conf
#CFLAGS += -I../Core/cmsis
#CFLAGS += -I../Core/stm32
#CFLAGS += -I../StdPeriph/inc
#CFLAGS += -I../FreeRTOS/inc

#output name
LIBNAME = libcolor_tools.a

#rules
include $(ROOTDIR)/rules.mk
